import { Listing } from './types';

// Shown only while the Emlakie API is not yet live. Every card is labeled
// "Sample" in the UI and the data disappears as soon as the API responds.
export const sampleListings: Listing[] = [
  {
    id: 'sample-1',
    title: 'Sunny 3BR Home with Large Backyard',
    description:
      'Bright, recently updated single-family home in a quiet neighborhood. Open kitchen with stainless appliances, two-car garage, and a large fenced backyard perfect for pets. Walking distance to parks and schools.',
    address: '2418 Brookside Ave',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93311',
    price: 2350,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1640,
    property_type: 'house',
    amenities: ['Central AC', 'Garage', 'Fenced Yard', 'Dishwasher', 'Pet Friendly'],
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80',
      'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
  {
    id: 'sample-2',
    title: 'Modern Downtown Apartment',
    description:
      'Stylish one-bedroom in the heart of downtown. Floor-to-ceiling windows, in-unit laundry, and a rooftop lounge. Steps from restaurants and nightlife.',
    address: '901 18th St, Unit 4B',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93301',
    price: 1495,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    property_type: 'apartment',
    amenities: ['In-Unit Laundry', 'Rooftop Lounge', 'Gym', 'Secure Entry'],
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
  {
    id: 'sample-3',
    title: 'Cozy Studio Near University',
    description:
      'Efficient studio with updated kitchenette and great natural light. Water and trash included. Ideal for students or commuters.',
    address: '3506 Q St',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93304',
    price: 995,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 410,
    property_type: 'studio',
    amenities: ['Utilities Included', 'On-Site Parking', 'Laundry Room'],
    photos: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
  {
    id: 'sample-4',
    title: 'Spacious 4BR Family Home with Pool',
    description:
      'Executive home in the Seven Oaks area. Gourmet kitchen, formal dining, sparkling pool with covered patio, and a three-car garage.',
    address: '11204 Vista Del Rio Dr',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93311',
    price: 3200,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2780,
    property_type: 'house',
    amenities: ['Pool', 'Central AC', '3-Car Garage', 'Gourmet Kitchen', 'Covered Patio'],
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
  {
    id: 'sample-5',
    title: 'Renovated 2BR Townhouse with Garage',
    description:
      'Two-story townhouse with brand-new flooring and paint. Private patio, attached garage, and community pool access.',
    address: '7409 Hanover Ln',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93309',
    price: 1750,
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1120,
    property_type: 'townhouse',
    amenities: ['Attached Garage', 'Community Pool', 'Private Patio', 'New Flooring'],
    photos: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
  {
    id: 'sample-6',
    title: 'Charming 2BR Condo with Mountain Views',
    description:
      'Top-floor condo with vaulted ceilings, fireplace, and a balcony overlooking the foothills. Covered parking and water included.',
    address: '5301 Lennox Ave, Unit 210',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93309',
    price: 1595,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 940,
    property_type: 'condo',
    amenities: ['Balcony', 'Fireplace', 'Covered Parking', 'Water Included'],
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&q=80',
    ],
    status: 'active',
    isSample: true,
  },
];
