// Top US cities by population — used to pre-generate city rental pages
// Slugs follow the same rule as getAllCities: lowercase, spaces→hyphens, non-alphanum stripped
export interface UsCityEntry {
  city: string;
  state: string; // 2-letter abbreviation
  slug: string;
}

export const US_CITIES: UsCityEntry[] = [
  { city: 'New York', state: 'NY', slug: 'new-york' },
  { city: 'Los Angeles', state: 'CA', slug: 'los-angeles' },
  { city: 'Chicago', state: 'IL', slug: 'chicago' },
  { city: 'Houston', state: 'TX', slug: 'houston' },
  { city: 'Phoenix', state: 'AZ', slug: 'phoenix' },
  { city: 'Philadelphia', state: 'PA', slug: 'philadelphia' },
  { city: 'San Antonio', state: 'TX', slug: 'san-antonio' },
  { city: 'San Diego', state: 'CA', slug: 'san-diego' },
  { city: 'Dallas', state: 'TX', slug: 'dallas' },
  { city: 'San Jose', state: 'CA', slug: 'san-jose' },
  { city: 'Austin', state: 'TX', slug: 'austin' },
  { city: 'Jacksonville', state: 'FL', slug: 'jacksonville' },
  { city: 'Fort Worth', state: 'TX', slug: 'fort-worth' },
  { city: 'Columbus', state: 'OH', slug: 'columbus' },
  { city: 'Charlotte', state: 'NC', slug: 'charlotte' },
  { city: 'Indianapolis', state: 'IN', slug: 'indianapolis' },
  { city: 'San Francisco', state: 'CA', slug: 'san-francisco' },
  { city: 'Seattle', state: 'WA', slug: 'seattle' },
  { city: 'Denver', state: 'CO', slug: 'denver' },
  { city: 'Nashville', state: 'TN', slug: 'nashville' },
  { city: 'Oklahoma City', state: 'OK', slug: 'oklahoma-city' },
  { city: 'El Paso', state: 'TX', slug: 'el-paso' },
  { city: 'Washington', state: 'DC', slug: 'washington' },
  { city: 'Las Vegas', state: 'NV', slug: 'las-vegas' },
  { city: 'Louisville', state: 'KY', slug: 'louisville' },
  { city: 'Memphis', state: 'TN', slug: 'memphis' },
  { city: 'Portland', state: 'OR', slug: 'portland' },
  { city: 'Baltimore', state: 'MD', slug: 'baltimore' },
  { city: 'Milwaukee', state: 'WI', slug: 'milwaukee' },
  { city: 'Albuquerque', state: 'NM', slug: 'albuquerque' },
  { city: 'Tucson', state: 'AZ', slug: 'tucson' },
  { city: 'Fresno', state: 'CA', slug: 'fresno' },
  { city: 'Mesa', state: 'AZ', slug: 'mesa' },
  { city: 'Sacramento', state: 'CA', slug: 'sacramento' },
  { city: 'Kansas City', state: 'MO', slug: 'kansas-city' },
  { city: 'Atlanta', state: 'GA', slug: 'atlanta' },
  { city: 'Omaha', state: 'NE', slug: 'omaha' },
  { city: 'Colorado Springs', state: 'CO', slug: 'colorado-springs' },
  { city: 'Raleigh', state: 'NC', slug: 'raleigh' },
  { city: 'Long Beach', state: 'CA', slug: 'long-beach' },
  { city: 'Virginia Beach', state: 'VA', slug: 'virginia-beach' },
  { city: 'Minneapolis', state: 'MN', slug: 'minneapolis' },
  { city: 'Tampa', state: 'FL', slug: 'tampa' },
  { city: 'New Orleans', state: 'LA', slug: 'new-orleans' },
  { city: 'Arlington', state: 'TX', slug: 'arlington' },
  { city: 'Bakersfield', state: 'CA', slug: 'bakersfield' },
  { city: 'Honolulu', state: 'HI', slug: 'honolulu' },
  { city: 'Anaheim', state: 'CA', slug: 'anaheim' },
  { city: 'Aurora', state: 'CO', slug: 'aurora' },
  { city: 'Santa Ana', state: 'CA', slug: 'santa-ana' },
  { city: 'Corpus Christi', state: 'TX', slug: 'corpus-christi' },
  { city: 'Riverside', state: 'CA', slug: 'riverside' },
  { city: 'Lexington', state: 'KY', slug: 'lexington' },
  { city: 'St. Louis', state: 'MO', slug: 'st-louis' },
  { city: 'Pittsburgh', state: 'PA', slug: 'pittsburgh' },
  { city: 'Stockton', state: 'CA', slug: 'stockton' },
  { city: 'Anchorage', state: 'AK', slug: 'anchorage' },
  { city: 'Cincinnati', state: 'OH', slug: 'cincinnati' },
  { city: 'St. Paul', state: 'MN', slug: 'st-paul' },
  { city: 'Greensboro', state: 'NC', slug: 'greensboro' },
  { city: 'Toledo', state: 'OH', slug: 'toledo' },
  { city: 'Newark', state: 'NJ', slug: 'newark' },
  { city: 'Plano', state: 'TX', slug: 'plano' },
  { city: 'Henderson', state: 'NV', slug: 'henderson' },
  { city: 'Orlando', state: 'FL', slug: 'orlando' },
  { city: 'Jersey City', state: 'NJ', slug: 'jersey-city' },
  { city: 'Chandler', state: 'AZ', slug: 'chandler' },
  { city: 'St. Petersburg', state: 'FL', slug: 'st-petersburg' },
  { city: 'Laredo', state: 'TX', slug: 'laredo' },
  { city: 'Norfolk', state: 'VA', slug: 'norfolk' },
  { city: 'Madison', state: 'WI', slug: 'madison' },
  { city: 'Durham', state: 'NC', slug: 'durham' },
  { city: 'Lubbock', state: 'TX', slug: 'lubbock' },
  { city: 'Winston-Salem', state: 'NC', slug: 'winston-salem' },
  { city: 'Garland', state: 'TX', slug: 'garland' },
  { city: 'Glendale', state: 'AZ', slug: 'glendale' },
  { city: 'Hialeah', state: 'FL', slug: 'hialeah' },
  { city: 'Reno', state: 'NV', slug: 'reno' },
  { city: 'Baton Rouge', state: 'LA', slug: 'baton-rouge' },
  { city: 'Irvine', state: 'CA', slug: 'irvine' },
  { city: 'Chesapeake', state: 'VA', slug: 'chesapeake' },
  { city: 'Scottsdale', state: 'AZ', slug: 'scottsdale' },
  { city: 'North Las Vegas', state: 'NV', slug: 'north-las-vegas' },
  { city: 'Fremont', state: 'CA', slug: 'fremont' },
  { city: 'Gilbert', state: 'AZ', slug: 'gilbert' },
  { city: 'San Bernardino', state: 'CA', slug: 'san-bernardino' },
  { city: 'Birmingham', state: 'AL', slug: 'birmingham' },
  { city: 'Rochester', state: 'NY', slug: 'rochester' },
  { city: 'Richmond', state: 'VA', slug: 'richmond' },
  { city: 'Spokane', state: 'WA', slug: 'spokane' },
  { city: 'Des Moines', state: 'IA', slug: 'des-moines' },
  { city: 'Montgomery', state: 'AL', slug: 'montgomery' },
  { city: 'Modesto', state: 'CA', slug: 'modesto' },
  { city: 'Fayetteville', state: 'NC', slug: 'fayetteville' },
  { city: 'Tacoma', state: 'WA', slug: 'tacoma' },
  { city: 'Shreveport', state: 'LA', slug: 'shreveport' },
  { city: 'Fontana', state: 'CA', slug: 'fontana' },
  { city: 'Moreno Valley', state: 'CA', slug: 'moreno-valley' },
  { city: 'Glendale', state: 'CA', slug: 'glendale-ca' },
  { city: 'Akron', state: 'OH', slug: 'akron' },
  { city: 'Yonkers', state: 'NY', slug: 'yonkers' },
  { city: 'Huntington Beach', state: 'CA', slug: 'huntington-beach' },
  { city: 'Little Rock', state: 'AR', slug: 'little-rock' },
  { city: 'Augusta', state: 'GA', slug: 'augusta' },
  { city: 'Columbus', state: 'GA', slug: 'columbus-ga' },
  { city: 'Grand Rapids', state: 'MI', slug: 'grand-rapids' },
  { city: 'Oxnard', state: 'CA', slug: 'oxnard' },
  { city: 'Tallahassee', state: 'FL', slug: 'tallahassee' },
  { city: 'Knoxville', state: 'TN', slug: 'knoxville' },
  { city: 'Worcester', state: 'MA', slug: 'worcester' },
  { city: 'Newport News', state: 'VA', slug: 'newport-news' },
  { city: 'Huntsville', state: 'AL', slug: 'huntsville' },
  { city: 'Providence', state: 'RI', slug: 'providence' },
  { city: 'Garden Grove', state: 'CA', slug: 'garden-grove' },
  { city: 'Oceanside', state: 'CA', slug: 'oceanside' },
  { city: 'Fort Lauderdale', state: 'FL', slug: 'fort-lauderdale' },
  { city: 'Rancho Cucamonga', state: 'CA', slug: 'rancho-cucamonga' },
  { city: 'Santa Clarita', state: 'CA', slug: 'santa-clarita' },
  { city: 'Vancouver', state: 'WA', slug: 'vancouver' },
  { city: 'Tempe', state: 'AZ', slug: 'tempe' },
  { city: 'Cape Coral', state: 'FL', slug: 'cape-coral' },
  { city: 'Sioux Falls', state: 'SD', slug: 'sioux-falls' },
  { city: 'Peoria', state: 'AZ', slug: 'peoria' },
  { city: 'Springfield', state: 'MO', slug: 'springfield' },
  { city: 'Chattanooga', state: 'TN', slug: 'chattanooga' },
  { city: 'Fort Wayne', state: 'IN', slug: 'fort-wayne' },
  { city: 'Ontario', state: 'CA', slug: 'ontario' },
  { city: 'Elk Grove', state: 'CA', slug: 'elk-grove' },
  { city: 'Eugene', state: 'OR', slug: 'eugene' },
  { city: 'Pembroke Pines', state: 'FL', slug: 'pembroke-pines' },
  { city: 'Salem', state: 'OR', slug: 'salem' },
  { city: 'Cary', state: 'NC', slug: 'cary' },
  { city: 'Corona', state: 'CA', slug: 'corona' },
  { city: 'Springfield', state: 'MA', slug: 'springfield-ma' },
  { city: 'Fort Collins', state: 'CO', slug: 'fort-collins' },
  { city: 'Jackson', state: 'MS', slug: 'jackson' },
  { city: 'Alexandria', state: 'VA', slug: 'alexandria' },
  { city: 'Hayward', state: 'CA', slug: 'hayward' },
  { city: 'Lancaster', state: 'CA', slug: 'lancaster' },
  { city: 'Salinas', state: 'CA', slug: 'salinas' },
  { city: 'Palmdale', state: 'CA', slug: 'palmdale' },
  { city: 'Sunnyvale', state: 'CA', slug: 'sunnyvale' },
  { city: 'Pomona', state: 'CA', slug: 'pomona' },
  { city: 'Escondido', state: 'CA', slug: 'escondido' },
  { city: 'Kansas City', state: 'KS', slug: 'kansas-city-ks' },
  { city: 'Savannah', state: 'GA', slug: 'savannah' },
  { city: 'Surprise', state: 'AZ', slug: 'surprise' },
  { city: 'Pasadena', state: 'TX', slug: 'pasadena' },
  { city: 'Rockford', state: 'IL', slug: 'rockford' },
  { city: 'Torrance', state: 'CA', slug: 'torrance' },
  { city: 'Paterson', state: 'NJ', slug: 'paterson' },
  { city: 'Bridgeport', state: 'CT', slug: 'bridgeport' },
  { city: 'McAllen', state: 'TX', slug: 'mcallen' },
  { city: 'Macon', state: 'GA', slug: 'macon' },
  { city: 'Syracuse', state: 'NY', slug: 'syracuse' },
  { city: 'Mesquite', state: 'TX', slug: 'mesquite' },
  { city: 'Lakewood', state: 'CO', slug: 'lakewood' },
  { city: 'Clarksville', state: 'TN', slug: 'clarksville' },
  { city: 'Killeen', state: 'TX', slug: 'killeen' },
  { city: 'Roseville', state: 'CA', slug: 'roseville' },
  { city: 'Hollywood', state: 'FL', slug: 'hollywood' },
  { city: 'Pasadena', state: 'CA', slug: 'pasadena-ca' },
  { city: 'Dayton', state: 'OH', slug: 'dayton' },
  { city: 'Bellevue', state: 'WA', slug: 'bellevue' },
  { city: 'Joliet', state: 'IL', slug: 'joliet' },
  { city: 'Naperville', state: 'IL', slug: 'naperville' },
  { city: 'Murfreesboro', state: 'TN', slug: 'murfreesboro' },
  { city: 'Escondido', state: 'CA', slug: 'escondido' },
  { city: 'Gainesville', state: 'FL', slug: 'gainesville' },
  { city: 'Warren', state: 'MI', slug: 'warren' },
  { city: 'Hampton', state: 'VA', slug: 'hampton' },
  { city: 'West Valley City', state: 'UT', slug: 'west-valley-city' },
  { city: 'Columbia', state: 'SC', slug: 'columbia' },
  { city: 'Sterling Heights', state: 'MI', slug: 'sterling-heights' },
  { city: 'Cedar Rapids', state: 'IA', slug: 'cedar-rapids' },
  { city: 'Topeka', state: 'KS', slug: 'topeka' },
  { city: 'Thousand Oaks', state: 'CA', slug: 'thousand-oaks' },
  { city: 'Visalia', state: 'CA', slug: 'visalia' },
  { city: 'Elizabeth', state: 'NJ', slug: 'elizabeth' },
  { city: 'Simi Valley', state: 'CA', slug: 'simi-valley' },
  { city: 'Concord', state: 'CA', slug: 'concord' },
  { city: 'Hartford', state: 'CT', slug: 'hartford' },
  { city: 'Roseville', state: 'CA', slug: 'roseville' },
  { city: 'Coral Springs', state: 'FL', slug: 'coral-springs' },
  { city: 'Stamford', state: 'CT', slug: 'stamford' },
  { city: 'Victorville', state: 'CA', slug: 'victorville' },
  { city: 'Olathe', state: 'KS', slug: 'olathe' },
  { city: 'Denton', state: 'TX', slug: 'denton' },
  { city: 'Waco', state: 'TX', slug: 'waco' },
  { city: 'Columbia', state: 'MO', slug: 'columbia-mo' },
  { city: 'Thornton', state: 'CO', slug: 'thornton' },
  { city: 'Abilene', state: 'TX', slug: 'abilene' },
  { city: 'Beaumont', state: 'TX', slug: 'beaumont' },
  { city: 'Independence', state: 'MO', slug: 'independence' },
  { city: 'Peoria', state: 'IL', slug: 'peoria-il' },
  { city: 'Ann Arbor', state: 'MI', slug: 'ann-arbor' },
  { city: 'Provo', state: 'UT', slug: 'provo' },
  { city: 'Inglewood', state: 'CA', slug: 'inglewood' },
  { city: 'Midland', state: 'TX', slug: 'midland' },
  { city: 'Manchester', state: 'NH', slug: 'manchester' },
  { city: 'Murrieta', state: 'CA', slug: 'murrieta' },
  { city: 'Elgin', state: 'IL', slug: 'elgin' },
  { city: 'Lansing', state: 'MI', slug: 'lansing' },
  { city: 'Downey', state: 'CA', slug: 'downey' },
  { city: 'Costa Mesa', state: 'CA', slug: 'costa-mesa' },
  { city: 'Miami Gardens', state: 'FL', slug: 'miami-gardens' },
  { city: 'West Palm Beach', state: 'FL', slug: 'west-palm-beach' },
  { city: 'Clearwater', state: 'FL', slug: 'clearwater' },
  { city: 'Arvada', state: 'CO', slug: 'arvada' },
  { city: 'Cambridge', state: 'MA', slug: 'cambridge' },
  { city: 'Lowell', state: 'MA', slug: 'lowell' },
  { city: 'Erie', state: 'PA', slug: 'erie' },
  { city: 'High Point', state: 'NC', slug: 'high-point' },
  { city: 'Round Rock', state: 'TX', slug: 'round-rock' },
  { city: 'Waterbury', state: 'CT', slug: 'waterbury' },
  { city: 'West Jordan', state: 'UT', slug: 'west-jordan' },
  { city: 'Centennial', state: 'CO', slug: 'centennial' },
  { city: 'Glendale', state: 'CA', slug: 'glendale-ca' },
  { city: 'Rochester', state: 'MN', slug: 'rochester-mn' },
  { city: 'Billings', state: 'MT', slug: 'billings' },
  { city: 'Boulder', state: 'CO', slug: 'boulder' },
  { city: 'West Covina', state: 'CA', slug: 'west-covina' },
  { city: 'Norwalk', state: 'CA', slug: 'norwalk' },
  { city: 'Everett', state: 'WA', slug: 'everett' },
  { city: 'Burbank', state: 'CA', slug: 'burbank' },
  { city: 'El Monte', state: 'CA', slug: 'el-monte' },
  { city: 'Palm Bay', state: 'FL', slug: 'palm-bay' },
  { city: 'Clovis', state: 'CA', slug: 'clovis' },
  { city: 'Antioch', state: 'CA', slug: 'antioch' },
  { city: 'Temecula', state: 'CA', slug: 'temecula' },
  { city: 'Pueblo', state: 'CO', slug: 'pueblo' },
  { city: 'McKinney', state: 'TX', slug: 'mckinney' },
  { city: 'Frisco', state: 'TX', slug: 'frisco' },
  { city: 'Carrollton', state: 'TX', slug: 'carrollton' },
  { city: 'Miramar', state: 'FL', slug: 'miramar' },
  { city: 'Amarillo', state: 'TX', slug: 'amarillo' },
  { city: 'Overland Park', state: 'KS', slug: 'overland-park' },
  { city: 'Brownsville', state: 'TX', slug: 'brownsville' },
  { city: 'Grand Prairie', state: 'TX', slug: 'grand-prairie' },
  { city: 'Tallahassee', state: 'FL', slug: 'tallahassee' },
  { city: 'Peoria', state: 'AZ', slug: 'peoria-az' },
  { city: 'Santa Rosa', state: 'CA', slug: 'santa-rosa' },
  { city: 'Rancho Cucamonga', state: 'CA', slug: 'rancho-cucamonga' },
  { city: 'Oxnard', state: 'CA', slug: 'oxnard' },
  { city: 'Oceanside', state: 'CA', slug: 'oceanside' },
  { city: 'Garden Grove', state: 'CA', slug: 'garden-grove' },
  { city: 'Ontario', state: 'CA', slug: 'ontario' },
  { city: 'Santa Clara', state: 'CA', slug: 'santa-clara' },
  { city: 'Fullerton', state: 'CA', slug: 'fullerton' },
  { city: 'Warren', state: 'MI', slug: 'warren' },
  { city: 'Hampton', state: 'VA', slug: 'hampton' },
  { city: 'Berkeley', state: 'CA', slug: 'berkeley' },
  { city: 'Naperville', state: 'IL', slug: 'naperville' },
  { city: 'Knoxville', state: 'TN', slug: 'knoxville' },
  { city: 'Tempe', state: 'AZ', slug: 'tempe' },
  { city: 'Cape Coral', state: 'FL', slug: 'cape-coral' },
  { city: 'Eugene', state: 'OR', slug: 'eugene' },
  { city: 'Peoria', state: 'AZ', slug: 'peoria-az' },
  { city: 'Miami', state: 'FL', slug: 'miami' },
  { city: 'Cleveland', state: 'OH', slug: 'cleveland' },
  { city: 'Wichita', state: 'KS', slug: 'wichita' },
  { city: 'Minneapolis', state: 'MN', slug: 'minneapolis' },
  { city: 'Oakland', state: 'CA', slug: 'oakland' },
  { city: 'Tulsa', state: 'OK', slug: 'tulsa' },
  { city: 'Arlington', state: 'VA', slug: 'arlington-va' },
  { city: 'Bakersfield', state: 'CA', slug: 'bakersfield' },
  { city: 'New Haven', state: 'CT', slug: 'new-haven' },
  { city: 'Buffalo', state: 'NY', slug: 'buffalo' },
  { city: 'Chandler', state: 'AZ', slug: 'chandler' },
  { city: 'Aurora', state: 'IL', slug: 'aurora-il' },
  { city: 'Anaheim', state: 'CA', slug: 'anaheim' },
  { city: 'Santa Ana', state: 'CA', slug: 'santa-ana' },
  { city: 'Corpus Christi', state: 'TX', slug: 'corpus-christi' },
  { city: 'Riverside', state: 'CA', slug: 'riverside' },
  { city: 'St. Louis', state: 'MO', slug: 'st-louis' },
  { city: 'Lexington', state: 'KY', slug: 'lexington' },
  { city: 'Pittsburgh', state: 'PA', slug: 'pittsburgh' },
  { city: 'Stockton', state: 'CA', slug: 'stockton' },
  { city: 'Anchorage', state: 'AK', slug: 'anchorage' },
  { city: 'Cincinnati', state: 'OH', slug: 'cincinnati' },
  { city: 'Greensboro', state: 'NC', slug: 'greensboro' },
  { city: 'Toledo', state: 'OH', slug: 'toledo' },
  { city: 'Newark', state: 'NJ', slug: 'newark' },
  { city: 'Plano', state: 'TX', slug: 'plano' },
  { city: 'Henderson', state: 'NV', slug: 'henderson' },
  { city: 'Orlando', state: 'FL', slug: 'orlando' },
  { city: 'Norfolk', state: 'VA', slug: 'norfolk' },
  { city: 'Madison', state: 'WI', slug: 'madison' },
  { city: 'Durham', state: 'NC', slug: 'durham' },
  { city: 'Lubbock', state: 'TX', slug: 'lubbock' },
  { city: 'Reno', state: 'NV', slug: 'reno' },
  { city: 'Baton Rouge', state: 'LA', slug: 'baton-rouge' },
  { city: 'Irvine', state: 'CA', slug: 'irvine' },
  { city: 'Chesapeake', state: 'VA', slug: 'chesapeake' },
  { city: 'Scottsdale', state: 'AZ', slug: 'scottsdale' },
  { city: 'Fremont', state: 'CA', slug: 'fremont' },
  { city: 'Gilbert', state: 'AZ', slug: 'gilbert' },
  { city: 'San Bernardino', state: 'CA', slug: 'san-bernardino' },
  { city: 'Birmingham', state: 'AL', slug: 'birmingham' },
  { city: 'Spokane', state: 'WA', slug: 'spokane' },
  { city: 'Des Moines', state: 'IA', slug: 'des-moines' },
  { city: 'Montgomery', state: 'AL', slug: 'montgomery' },
  { city: 'Modesto', state: 'CA', slug: 'modesto' },
  { city: 'Fayetteville', state: 'NC', slug: 'fayetteville' },
  { city: 'Tacoma', state: 'WA', slug: 'tacoma' },
  { city: 'Shreveport', state: 'LA', slug: 'shreveport' },
  { city: 'Fontana', state: 'CA', slug: 'fontana' },
  { city: 'Moreno Valley', state: 'CA', slug: 'moreno-valley' },
  { city: 'Akron', state: 'OH', slug: 'akron' },
  { city: 'Yonkers', state: 'NY', slug: 'yonkers' },
  { city: 'Huntington Beach', state: 'CA', slug: 'huntington-beach' },
  { city: 'Little Rock', state: 'AR', slug: 'little-rock' },
  { city: 'Augusta', state: 'GA', slug: 'augusta' },
  { city: 'Grand Rapids', state: 'MI', slug: 'grand-rapids' },
  { city: 'Tallahassee', state: 'FL', slug: 'tallahassee' },
  { city: 'Knoxville', state: 'TN', slug: 'knoxville' },
  { city: 'Worcester', state: 'MA', slug: 'worcester' },
  { city: 'Newport News', state: 'VA', slug: 'newport-news' },
  { city: 'Huntsville', state: 'AL', slug: 'huntsville' },
  { city: 'Providence', state: 'RI', slug: 'providence' },
  { city: 'Fort Lauderdale', state: 'FL', slug: 'fort-lauderdale' },
  { city: 'Savannah', state: 'GA', slug: 'savannah' },
  { city: 'Rockford', state: 'IL', slug: 'rockford' },
  { city: 'Torrance', state: 'CA', slug: 'torrance' },
  { city: 'Paterson', state: 'NJ', slug: 'paterson' },
  { city: 'Bridgeport', state: 'CT', slug: 'bridgeport' },
  { city: 'McAllen', state: 'TX', slug: 'mcallen' },
  { city: 'Macon', state: 'GA', slug: 'macon' },
  { city: 'Syracuse', state: 'NY', slug: 'syracuse' },
  { city: 'Mesquite', state: 'TX', slug: 'mesquite' },
  { city: 'Lakewood', state: 'CO', slug: 'lakewood' },
  { city: 'Clarksville', state: 'TN', slug: 'clarksville' },
  { city: 'Killeen', state: 'TX', slug: 'killeen' },
  { city: 'Hollywood', state: 'FL', slug: 'hollywood' },
  { city: 'Dayton', state: 'OH', slug: 'dayton' },
  { city: 'Joliet', state: 'IL', slug: 'joliet' },
  { city: 'Murfreesboro', state: 'TN', slug: 'murfreesboro' },
  { city: 'Gainesville', state: 'FL', slug: 'gainesville' },
  { city: 'Columbia', state: 'SC', slug: 'columbia' },
  { city: 'Sterling Heights', state: 'MI', slug: 'sterling-heights' },
  { city: 'Cedar Rapids', state: 'IA', slug: 'cedar-rapids' },
  { city: 'Topeka', state: 'KS', slug: 'topeka' },
  { city: 'Thousand Oaks', state: 'CA', slug: 'thousand-oaks' },
  { city: 'Visalia', state: 'CA', slug: 'visalia' },
  { city: 'Elizabeth', state: 'NJ', slug: 'elizabeth' },
  { city: 'Simi Valley', state: 'CA', slug: 'simi-valley' },
  { city: 'Concord', state: 'CA', slug: 'concord' },
  { city: 'Hartford', state: 'CT', slug: 'hartford' },
  { city: 'Coral Springs', state: 'FL', slug: 'coral-springs' },
  { city: 'Stamford', state: 'CT', slug: 'stamford' },
  { city: 'Victorville', state: 'CA', slug: 'victorville' },
  { city: 'Olathe', state: 'KS', slug: 'olathe' },
  { city: 'Denton', state: 'TX', slug: 'denton' },
  { city: 'Waco', state: 'TX', slug: 'waco' },
  { city: 'Thornton', state: 'CO', slug: 'thornton' },
  { city: 'Abilene', state: 'TX', slug: 'abilene' },
  { city: 'Beaumont', state: 'TX', slug: 'beaumont' },
  { city: 'Independence', state: 'MO', slug: 'independence' },
  { city: 'Ann Arbor', state: 'MI', slug: 'ann-arbor' },
  { city: 'Provo', state: 'UT', slug: 'provo' },
  { city: 'Inglewood', state: 'CA', slug: 'inglewood' },
  { city: 'Midland', state: 'TX', slug: 'midland' },
  { city: 'Manchester', state: 'NH', slug: 'manchester' },
  { city: 'Murrieta', state: 'CA', slug: 'murrieta' },
  { city: 'Elgin', state: 'IL', slug: 'elgin' },
  { city: 'Lansing', state: 'MI', slug: 'lansing' },
  { city: 'Downey', state: 'CA', slug: 'downey' },
  { city: 'Costa Mesa', state: 'CA', slug: 'costa-mesa' },
  { city: 'West Palm Beach', state: 'FL', slug: 'west-palm-beach' },
  { city: 'Clearwater', state: 'FL', slug: 'clearwater' },
  { city: 'Arvada', state: 'CO', slug: 'arvada' },
  { city: 'Cambridge', state: 'MA', slug: 'cambridge' },
  { city: 'Lowell', state: 'MA', slug: 'lowell' },
  { city: 'Erie', state: 'PA', slug: 'erie' },
  { city: 'High Point', state: 'NC', slug: 'high-point' },
  { city: 'Round Rock', state: 'TX', slug: 'round-rock' },
  { city: 'Waterbury', state: 'CT', slug: 'waterbury' },
  { city: 'West Jordan', state: 'UT', slug: 'west-jordan' },
  { city: 'Centennial', state: 'CO', slug: 'centennial' },
  { city: 'Billings', state: 'MT', slug: 'billings' },
  { city: 'Boulder', state: 'CO', slug: 'boulder' },
  { city: 'West Covina', state: 'CA', slug: 'west-covina' },
  { city: 'Norwalk', state: 'CA', slug: 'norwalk' },
  { city: 'Everett', state: 'WA', slug: 'everett' },
  { city: 'Burbank', state: 'CA', slug: 'burbank' },
  { city: 'El Monte', state: 'CA', slug: 'el-monte' },
  { city: 'Palm Bay', state: 'FL', slug: 'palm-bay' },
  { city: 'Clovis', state: 'CA', slug: 'clovis' },
  { city: 'Antioch', state: 'CA', slug: 'antioch' },
  { city: 'Temecula', state: 'CA', slug: 'temecula' },
  { city: 'Pueblo', state: 'CO', slug: 'pueblo' },
  { city: 'McKinney', state: 'TX', slug: 'mckinney' },
  { city: 'Frisco', state: 'TX', slug: 'frisco' },
  { city: 'Carrollton', state: 'TX', slug: 'carrollton' },
  { city: 'Miramar', state: 'FL', slug: 'miramar' },
  { city: 'Amarillo', state: 'TX', slug: 'amarillo' },
  { city: 'Overland Park', state: 'KS', slug: 'overland-park' },
  { city: 'Brownsville', state: 'TX', slug: 'brownsville' },
  { city: 'Grand Prairie', state: 'TX', slug: 'grand-prairie' },
  { city: 'Santa Rosa', state: 'CA', slug: 'santa-rosa' },
  { city: 'Santa Clara', state: 'CA', slug: 'santa-clara' },
  { city: 'Fullerton', state: 'CA', slug: 'fullerton' },
  { city: 'Berkeley', state: 'CA', slug: 'berkeley' },
  { city: 'New Haven', state: 'CT', slug: 'new-haven' },
  { city: 'Buffalo', state: 'NY', slug: 'buffalo' },
  { city: 'Oakland', state: 'CA', slug: 'oakland' },
  { city: 'Tulsa', state: 'OK', slug: 'tulsa' },
  { city: 'Wichita', state: 'KS', slug: 'wichita' },
  { city: 'Rochester', state: 'MN', slug: 'rochester-mn' },
  { city: 'Aurora', state: 'IL', slug: 'aurora-il' },
  // Pacific Northwest cities already in city-content
  { city: 'Federal Way', state: 'WA', slug: 'federal-way' },
  { city: 'Redmond', state: 'WA', slug: 'redmond' },
  { city: 'Kirkland', state: 'WA', slug: 'kirkland' },
  { city: 'Renton', state: 'WA', slug: 'renton' },
  { city: 'Kent', state: 'WA', slug: 'kent' },
  { city: 'Auburn', state: 'WA', slug: 'auburn' },
  // LA area
  { city: 'Beverly Hills', state: 'CA', slug: 'beverly-hills' },
  { city: 'West Hollywood', state: 'CA', slug: 'west-hollywood' },
  { city: 'Venice', state: 'CA', slug: 'venice' },
  { city: 'Winnetka', state: 'IL', slug: 'winnetka' },
  // Additional metros
  { city: 'Salt Lake City', state: 'UT', slug: 'salt-lake-city' },
  { city: 'Allentown', state: 'PA', slug: 'allentown' },
  { city: 'Boise', state: 'ID', slug: 'boise' },
  { city: 'Spokane Valley', state: 'WA', slug: 'spokane-valley' },
  { city: 'Fargo', state: 'ND', slug: 'fargo' },
  { city: 'Glendale Heights', state: 'IL', slug: 'glendale-heights' },
  { city: 'Shreveport', state: 'LA', slug: 'shreveport' },
  { city: 'Laredo', state: 'TX', slug: 'laredo' },
  { city: 'Hialeah', state: 'FL', slug: 'hialeah' },
  { city: 'North Las Vegas', state: 'NV', slug: 'north-las-vegas' },
  { city: 'Surprise', state: 'AZ', slug: 'surprise' },
  { city: 'Pasadena', state: 'TX', slug: 'pasadena' },
  { city: 'Miami Gardens', state: 'FL', slug: 'miami-gardens' },
  { city: 'Rochester', state: 'NY', slug: 'rochester' },
  { city: 'Sioux Falls', state: 'SD', slug: 'sioux-falls' },
  { city: 'Jackson', state: 'MS', slug: 'jackson' },
  { city: 'Fort Wayne', state: 'IN', slug: 'fort-wayne' },
  { city: 'Elk Grove', state: 'CA', slug: 'elk-grove' },
  { city: 'Pembroke Pines', state: 'FL', slug: 'pembroke-pines' },
  { city: 'Salem', state: 'OR', slug: 'salem' },
  { city: 'Cary', state: 'NC', slug: 'cary' },
  { city: 'Corona', state: 'CA', slug: 'corona' },
  { city: 'Fort Collins', state: 'CO', slug: 'fort-collins' },
  { city: 'Alexandria', state: 'VA', slug: 'alexandria' },
  { city: 'Hayward', state: 'CA', slug: 'hayward' },
  { city: 'Lancaster', state: 'CA', slug: 'lancaster' },
  { city: 'Salinas', state: 'CA', slug: 'salinas' },
  { city: 'Palmdale', state: 'CA', slug: 'palmdale' },
  { city: 'Sunnyvale', state: 'CA', slug: 'sunnyvale' },
  { city: 'Pomona', state: 'CA', slug: 'pomona' },
  { city: 'Escondido', state: 'CA', slug: 'escondido' },
  { city: 'Springfield', state: 'IL', slug: 'springfield-il' },
  { city: 'Peoria', state: 'IL', slug: 'peoria-il' },
  { city: 'Chattanooga', state: 'TN', slug: 'chattanooga' },
  { city: 'Columbus', state: 'GA', slug: 'columbus-ga' },
  { city: 'Vancouver', state: 'WA', slug: 'vancouver' },
  { city: 'Cape Coral', state: 'FL', slug: 'cape-coral' },
];

// Deduplicate by slug (some cities appear more than once above)
const seen = new Set<string>();
const deduped: UsCityEntry[] = [];
for (const c of US_CITIES) {
  if (!seen.has(c.slug)) {
    seen.add(c.slug);
    deduped.push(c);
  }
}
export const US_CITIES_UNIQUE = deduped;
