import { Application, Conversation, LandlordListing } from './types';

// Demo dashboard data, shown only in demo mode (no real account/API).
export const demoListings: LandlordListing[] = [
  {
    id: 'demo-1',
    title: 'Sunny 3BR Home with Large Backyard',
    address: '2418 Brookside Ave',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93311',
    price: 2350,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1640,
    property_type: 'house',
    amenities: ['Central AC', 'Garage', 'Fenced Yard'],
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80'],
    status: 'active',
    view_count: 342,
    applicant_count: 5,
    isSample: true,
  },
  {
    id: 'demo-2',
    title: 'Modern Downtown Apartment',
    address: '901 18th St, Unit 4B',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93301',
    price: 1495,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    property_type: 'apartment',
    amenities: ['In-Unit Laundry', 'Gym'],
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
    status: 'rented',
    view_count: 891,
    applicant_count: 12,
    isSample: true,
  },
  {
    id: 'demo-3',
    title: 'Renovated 2BR Townhouse with Garage',
    address: '7409 Hanover Ln',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93309',
    price: 1750,
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1120,
    property_type: 'townhouse',
    amenities: ['Attached Garage', 'Community Pool'],
    photos: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80'],
    status: 'paused',
    view_count: 127,
    applicant_count: 1,
    isSample: true,
  },
];

export const demoApplications: Application[] = [
  {
    id: 'demo-app-1',
    listing_id: 'demo-1',
    tenant_name: 'Maria G.',
    message:
      'Hi! My family of four is relocating to Bakersfield for work. We have excellent rental history and can move in on the 1st.',
    income: 7200,
    ai_match_score: 92,
    ai_summary: 'Strong applicant: income 3x rent, stable employment, no pets, flexible move-in.',
    status: 'pending',
    created_at: '2026-06-09T18:24:00Z',
  },
  {
    id: 'demo-app-2',
    listing_id: 'demo-1',
    tenant_name: 'Devon W.',
    message: 'Interested in the house — is the backyard fully fenced? I have one small dog.',
    income: 5100,
    ai_match_score: 78,
    ai_summary: 'Good fit: income above 2x rent, has a pet (listing allows pets).',
    status: 'pending',
    created_at: '2026-06-08T22:10:00Z',
  },
  {
    id: 'demo-app-3',
    listing_id: 'demo-1',
    tenant_name: 'Sam T.',
    message: 'Looking for a 6-month lease while my house is being built.',
    income: 4300,
    ai_match_score: 55,
    ai_summary: 'Partial fit: wants short-term lease; listing seeks 12-month minimum.',
    status: 'rejected',
    created_at: '2026-06-07T15:45:00Z',
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'demo-conv-1',
    listing_id: 'demo-1',
    listing_title: '2418 Brookside Ave',
    tenant_name: 'Maria G.',
    last_message: 'Thank you! Would Saturday morning work for a tour?',
    last_message_at: '2026-06-10T16:47:00Z',
    unread: true,
  },
  {
    id: 'demo-conv-2',
    listing_id: 'demo-1',
    listing_title: '2418 Brookside Ave',
    tenant_name: 'Devon W.',
    last_message: 'Great, I will send my application tonight.',
    last_message_at: '2026-06-09T21:03:00Z',
    unread: false,
  },
  {
    id: 'demo-conv-3',
    listing_id: 'demo-2',
    listing_title: '901 18th St, Unit 4B',
    tenant_name: 'Jasmine P.',
    last_message: 'Will do first thing tomorrow morning. Thanks for the timely response!',
    last_message_at: '2026-06-08T14:30:00Z',
    unread: false,
  },
];
